config/routes.rb
Hguev::Application.routes.draw do
  resources :lectures do
    resources :comments
  end

  get "home/index"

  root :to => "home#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :lecture
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  validates :name, :presence => true
  validates :code, :presence => true
  validates :semester, :presence => true
  validates :professor, :presence =>true

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @lecture = Lecture.find(params[:lecture_id])
    @comment = @lecture.comments.create(params[:comment])

	@count = 0
	@gpa = 0
	@hard = 0
	@score = 0
	
    @lecture.comments.each do |comment|
      @gpa = @gpa.to_f + comment.gpa
      @hard = @hard.to_f + comment.hard
      @score = @score.to_f + comment.score
	  @count = @count.to_i + 1
    end

	@lecture.gpa = @gpa.to_f / @count
	@lecture.hard = @hard.to_f / @count
	@lecture.score = @score.to_f / @count
    @lecture.save

    redirect_to lecture_path(@lecture)
  end  

  def destroy
    @lecture = Lecture.find(params[:lecture_id])
    @comment = @lecture.comments.find(params[:id])
    @comment.destroy
    redirect_to lecture_path(@lecture)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  # GET /lectures
  # GET /lectures.xml
  def index
    @lectures = Lecture.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lectures }
    end
  end

  # GET /lectures/1
  # GET /lectures/1.xml
  def show
    @lecture = Lecture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @lecture }
    end
  end

  # GET /lectures/new
  # GET /lectures/new.xml
  def new
    @lecture = Lecture.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @lecture }
    end
  end

  # GET /lectures/1/edit
  def edit
    @lecture = Lecture.find(params[:id])
  end

  # POST /lectures
  # POST /lectures.xml
  def create
    @lecture = Lecture.new(params[:lecture])

    respond_to do |format|
      if @lecture.save
        format.html { redirect_to(@lecture, :notice => 'Lecture was successfully created.') }
        format.xml  { render :xml => @lecture, :status => :created, :location => @lecture }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @lecture.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lectures/1
  # PUT /lectures/1.xml
  def update
    @lecture = Lecture.find(params[:id])

    respond_to do |format|
      if @lecture.update_attributes(params[:lecture])
        format.html { redirect_to(@lecture, :notice => 'Lecture was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @lecture.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1
  # DELETE /lectures/1.xml
  def destroy
    @lecture = Lecture.find(params[:id])
    @lecture.destroy

    respond_to do |format|
      format.html { redirect_to(lectures_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/comments/_comment.html.erb
<p>
  <b>글쓴이:</b>
  <%= comment.commenter %>
  <b>한마디:</b>
  <%= comment.body %>
</p>
<div>
	<span>
	  <b>난이도:</b>
	  <%= comment.hard %>
	</span>
	<span>
	  <b>학점만족도:</b>
	  <%= comment.gpa %>
	</span>
	<span>
	  <b>평점:</b>
	  <%= comment.score %>
	</span>
</div>
<p>
  <%= link_to 'Destroy Comment', [comment.lecture, comment],
              :confirm => 'Are you sure?',
              :method => :delete %>
</p>              

app/views/comments/_form.html.erb
<%= form_for([@lecture, @lecture.comments.build]) do |f| %>
  <div class="field">
    글쓴이<br />
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    수업평가<br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    난이도<br />
    <%= f.range_field :hard , :in => 1..5, :step => '1'%>
  </div>
  <div class="field">
    학점만족도<br />
    <%= f.range_field :gpa , :in => 1..5, :step => '1'%>
  </div>
  <div class="field">
    평점<br />
    <%= f.range_field :score , :in => 1..5, :step => '1'%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hguev</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body style="background: #EEEEEE;">


<%= yield %>

</body>
</html>

app/views/lectures/_form.html.erb
<%= form_for(@lecture) do |f| %>
  <% if @lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
      <% @lecture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :semester %><br />
    <%= f.date_select :semester %>
  </div>
  <div class="field">
    <%= f.label :professor %><br />
    <%= f.text_field :professor %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.text_field :score %>
  </div>
  <div class="field">
    <%= f.label :gpa %><br />
    <%= f.text_field :gpa %>
  </div>
  <div class="field">
    <%= f.label :hard %><br />
    <%= f.text_field :hard %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lectures/edit.html.erb
<h1>Editing lecture</h1>

<%= render 'form' %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', lectures_path %>

app/views/lectures/index.html.erb
<h1>Listing lectures</h1>

<table>
  <tr>
    <th>강의명</th>
    <th>코드</th>
    <th>학기</th>
    <th>교수</th>
    <th>난이도</th>
    <th>학점만족도</th>
    <th>평점</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lectures.each do |lecture| %>
  <tr>
    <td><%= lecture.name %></td>
    <td><%= lecture.code %></td>
    <td><%= lecture.semester %></td>
    <td><%= lecture.professor %></td>
    <td><%= number_with_precision(lecture.hard, precision: 2) %></td>
    <td><%= number_with_precision(lecture.gpa, precision: 2) %></td>
    <td><%= number_with_precision(lecture.score, precision: 2) %></td>
    <td><%= link_to 'Show', lecture %></td>
    <td><%= link_to 'Edit', edit_lecture_path(lecture) %></td>
    <td><%= link_to 'Destroy', lecture, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lecture', new_lecture_path %>

app/views/lectures/new.html.erb
<h1>New lecture</h1>

<%= render 'form' %>

<%= link_to 'Back', lectures_path %>

app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <b>수업명:</b>
  <%= @lecture.name %>
</h1>

<p>
  <b>Professor:</b>
  <%= @lecture.professor %>
</p>

<p>
  <b>Code:</b>
  <%= @lecture.code %>
</p>

<p>
  <b>Semester:</b>
  <%= @lecture.semester %>
</p>

<h3>
  <b>학점만족도:</b>
  <%= number_with_precision(@lecture.gpa, precision: 2) %>

<br>
  <b>난이도:</b>
  <%= number_with_precision(@lecture.hard, precision: 2) %>
<br>
  <b>평점:</b>
  <%= number_with_precision(@lecture.score, precision: 2) %>
</h3>

<h2>다른 학우들의 평가</h2>
<%= render @lecture.comments %>

<h2>강의 평가하기</h2>
<%= render "comments/form" %>



<%= link_to 'Edit', edit_lecture_path(@lecture) %> |
<%= link_to 'Back', lectures_path %>